baseURL = 'https://blog.varsni.com/'
languageCode = 'en-us'
title = "Varsni's Blog"
theme = "paper"
[params]
   github = "its-ammu"
   rss = true
   math = true  
   enableEmoji = true      

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
